In [3]:
import numpy as np

a = np.random.rand(5)

In [4]:
print(a)

[0.65815446 0.72810356 0.75093817 0.67280917 0.30023973]


In [5]:
print(a.shape)

(5,)


In [6]:
print(a.T)

[0.65815446 0.72810356 0.75093817 0.67280917 0.30023973]


In [7]:
print(np.dot(a, a.T))

2.070026288544908


In [8]:
a = np.random.rand(5, 1)

In [9]:
print(a)

[[0.42917898]
 [0.29309789]
 [0.14471069]
 [0.65054918]
 [0.38845784]]


In [10]:
print(a.T)

[[0.42917898 0.29309789 0.14471069 0.65054918 0.38845784]]


In [11]:
print(np.dot(a, a.T))

[[0.1841946  0.12579145 0.06210679 0.27920203 0.16671794]
 [0.12579145 0.08590637 0.0424144  0.19067459 0.11385617]
 [0.06210679 0.0424144  0.02094118 0.09414142 0.056214  ]
 [0.27920203 0.19067459 0.09414142 0.42321424 0.25271093]
 [0.16671794 0.11385617 0.056214   0.25271093 0.15089949]]
